# Generated by Django 4.0.1 on 2022-02-19 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_rename_cost_price_company_buy_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Instance marked deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Instance marked Active')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Extra Data')),
                ('buy_price', models.FloatField()),
                ('sold_price', models.FloatField()),
                ('profit', models.FloatField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
