# Generated by Django 4.0.1 on 2022-02-19 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Instance marked deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Instance marked Active')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Extra Data')),
                ('name', models.CharField(max_length=64)),
                ('is_stockable', models.BooleanField()),
                ('cost_price', models.FloatField(blank=True, null=True)),
                ('margin_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Instance marked deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Instance marked Active')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Extra Data')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_stockable', models.BooleanField()),
                ('company', models.ManyToManyField(blank=True, null=True, related_name='item_company', to='common.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FRCPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Instance marked deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Instance marked Active')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Extra Data')),
                ('price', models.IntegerField()),
                ('validity', models.TextField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frc_plans_company', to='common.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='frc_plans',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_frc_plans', to='common.FRCPlans'),
        ),
        migrations.AddField(
            model_name='company',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_item', to='common.item'),
        ),
    ]
