# Generated by Django 4.0.1 on 2022-02-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frcplans',
            name='validity',
            field=models.CharField(max_length=64),
        ),
    ]
