# Generated by Django 4.0.1 on 2022-02-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_frcplans_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='frcplans',
            name='instinctive',
            field=models.FloatField(default=0),
        ),
    ]
