# Generated by Django 4.0.1 on 2022-02-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_frcplans_instinctive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='cost_price',
            new_name='buy_price',
        ),
        migrations.AddField(
            model_name='company',
            name='is_margin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_company',
            field=models.BooleanField(default=True),
        ),
    ]
