# Generated by Django 4.0.1 on 2022-02-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_cost_price_company_buy_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='frcplans',
            unique_together={('company', 'price')},
        ),
    ]
