# Generated by Django 4.0.1 on 2022-02-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='comment',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
